name: Generate Sitemap

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # allows manual trigger

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1.10.4
        with:
          base-url: 'https://backflowservicesva.com'
          source-dir: 'public'
          output-file: 'public/sitemap.xml'
